#!/usr/bin/env python

# DIRT.
#
# Andy Mastbaum (amastbaum@gmail.com), August 2011

import sys
import signal
import settings
from core.log import log

def help():
    print \
'''Usage:

  dirt serve
  - Run the dirt remote execution server, which will dole out unfinished tasks
    in the database to available execution hosts.

  dirt updatenodes [host1] [host2] ...
  - Update stored system information on each host, adding the host to the
    database if necessary.
'''

def signal_handler(signal, frame):
    log.write('Caught SIGINT (Ctrl-C), Exiting.')
    # do something smart
    sys.exit(0)

def serve_forever():
    from core import helpers
    from core import load_balance
    from core import dbi
    signal.signal(signal.SIGINT, signal_handler)
    log.write('dirt is running...')

    db = dbi.DirtCouchDB(settings.couchdb_host, settings.couchdb_dbname)
    nodes = load_balance.round_robin(db)
    tasks = db.get_tasks()

    for id, taskname, taskid in tasks:
        node = nodes.next()
        log.write('%s : %s -> %s' % (id, taskname, node['hostname']))
        helpers.remote_execute(db, node, id, taskid, taskname)

if __name__ == '__main__':
    if len(sys.argv) < 2:
        help()
        sys.exit(1)

    if sys.argv[1] == 'serve':
        serve_forever()
    elif sys.argv[1] == 'updatenodes':
        import core.helpers
        nodes = sys.argv[2:]
        if len(nodes) == 0:
            help()
            sys.exit(1)
        core.helpers.node_recon(nodes, core.helpers.connect_to_db())
    else:
        help()
        sys.exit(0)

